language: objective-c
before_script:
- curl -sSL https://get.rvm.io | bash  
- source ~/.bashrc    
- source ~/.bash_profile  
- ruby -v    
#列出已知的ruby版本    
- rvm list known    
#安装 ruby-2.3.0    
- rvm reinstall ruby-2.3.0 
- brew update
- brew upgrade xctool
script: xctool test -project Tests/UnitTests.xcodeproj -scheme UnitTests -sdk iphonesimulator
